name: juicedates
description: Values dating revolution - 85% reply rate
version: 1.0.0+1
environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.1
  firebase_messaging: ^15.2.1
  http: ^1.2.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.5
  lottie: ^3.1.2
  audioplayers: ^6.1.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  flutter_card_swiper: ^7.0.0
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.3.1
  # google_sign_in removed
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
