services:
  - type: web
    name: juicedates-notify
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NOTIFY_API_KEY
        value: cUyczwQ8y7UWO64_5Y9_u5N2V37FxhUC
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false                # You paste this manually in the Render dashboard
