// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACP9h0Ts-UZk1sw9PHYFiUJ6DchkjbDyw',
    appId: '1:408134384062:web:77b25b3a22972e42df21ef',
    messagingSenderId: '408134384062',
    projectId: 'juicedates-2ebf0',
    authDomain: 'juicedates-2ebf0.firebaseapp.com',
    storageBucket: 'juicedates-2ebf0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKuul22MgNBbx1PyvhQAjU6Y1E6S2Pnic',
    appId: '1:408134384062:android:cfdf27d88d7c75bddf21ef',
    messagingSenderId: '408134384062',
    projectId: 'juicedates-2ebf0',
    storageBucket: 'juicedates-2ebf0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKkbyl64xKOqdbzi63Qv7TKhCKd4h4Re0',
    appId: '1:408134384062:ios:467483d9b80c47bddf21ef',
    messagingSenderId: '408134384062',
    projectId: 'juicedates-2ebf0',
    storageBucket: 'juicedates-2ebf0.firebasestorage.app',
    iosBundleId: 'com.juice.juicedates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKkbyl64xKOqdbzi63Qv7TKhCKd4h4Re0',
    appId: '1:408134384062:ios:467483d9b80c47bddf21ef',
    messagingSenderId: '408134384062',
    projectId: 'juicedates-2ebf0',
    storageBucket: 'juicedates-2ebf0.firebasestorage.app',
    iosBundleId: 'com.juice.juicedates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACP9h0Ts-UZk1sw9PHYFiUJ6DchkjbDyw',
    appId: '1:408134384062:web:7bfe86ba8544abe9df21ef',
    messagingSenderId: '408134384062',
    projectId: 'juicedates-2ebf0',
    authDomain: 'juicedates-2ebf0.firebaseapp.com',
    storageBucket: 'juicedates-2ebf0.firebasestorage.app',
  );
}
